In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [2]:
players_22 = pd.read_csv("C:/Users/Ansah/OneDrive - Ashesi University/Documents/Ashesi/Sem4/AI/Lab02_peniel.ansah/players_22-1.csv")
male_players = pd.read_csv("C:/Users/Ansah/OneDrive - Ashesi University/Documents/Ashesi/Sem4/AI/Lab02_peniel.ansah/male_players (legacy).csv")

C:\Users\Ansah\AppData\Local\Temp\ipykernel_10224\2151435904.py:1: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  players_22 = pd.read_csv("C:/Users/Ansah/OneDrive - Ashesi University/Documents/Ashesi/Sem4/AI/Lab02_peniel.ansah/players_22-1.csv")
C:\Users\Ansah\AppData\Local\Temp\ipykernel_10224\2151435904.py:2: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  male_players = pd.read_csv("C:/Users/Ansah/OneDrive - Ashesi University/Documents/Ashesi/Sem4/AI/Lab02_peniel.ansah/male_players (legacy).csv")

In [3]:
players_22.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [4]:
players_22.describe()

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,19239.000000,19239.000000,19239.000000,1.916500e+04,19178.000000,19239.000000,19239.000000,19239.000000,19178.000000,19178.000000,...,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,2132.000000
mean,231468.086959,65.772182,71.079370,2.850452e+06,9017.989363,25.210822,181.299704,74.943032,50580.498123,1.354364,...,57.929830,46.601746,48.045584,45.906700,16.406102,16.192474,16.055356,16.229274,16.491814,36.439962
std,27039.717497,6.880232,6.086213,7.613700e+06,19470.176724,4.748235,6.863179,7.069434,54401.868535,0.747865,...,12.159326,20.200807,21.232718,20.755683,17.574028,16.839528,16.564554,17.059779,17.884833,10.751563
min,41.000000,47.000000,49.000000,9.000000e+03,500.000000,16.000000,155.000000,49.000000,1.000000,1.000000,...,12.000000,4.000000,5.000000,5.000000,2.000000,2.000000,2.000000,2.000000,2.000000,15.000000
25%,214413.500000,61.000000,67.000000,4.750000e+05,1000.000000,21.000000,176.000000,70.000000,479.000000,1.000000,...,50.000000,29.000000,28.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,27.000000
50%,236543.000000,66.000000,71.000000,9.750000e+05,3000.000000,25.000000,181.000000,75.000000,1938.000000,1.000000,...,59.000000,52.000000,56.000000,53.000000,11.000000,11.000000,11.000000,11.000000,11.000000,36.000000
75%,253532.500000,70.000000,75.000000,2.000000e+06,8000.000000,29.000000,186.000000,80.000000,111139.000000,1.000000,...,66.000000,63.000000,65.000000,63.000000,14.000000,14.000000,14.000000,14.000000,14.000000,45.000000
max,264640.000000,93.000000,95.000000,1.940000e+08,350000.000000,54.000000,206.000000,110.000000,115820.000000,5.000000,...,96.000000,93.000000,93.000000,92.000000,91.000000,92.000000,93.000000,92.000000,90.000000,65.000000

In [5]:
players_22.info(verbose= True, show_counts= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Data columns (total 110 columns):
 #    Column                       Non-Null Count  Dtype
---   ------                       --------------  -----
 0    sofifa_id                    19239 non-null  int64
 1    player_url                   19239 non-null  object
 2    short_name                   19239 non-null  object
 3    long_name                    19239 non-null  object
 4    player_positions             19239 non-null  object
 5    overall                      19239 non-null  int64
 6    potential                    19239 non-null  int64
 7    value_eur                    19165 non-null  float64
 8    wage_eur                     19178 non-null  float64
 9    age                          19239 non-null  int64
 10   dob                          19239 non-null  object
 11   height_cm                    19239 non-null  int64
 12   weight_kg                    19239 non-null  int64
 13   club_team_id                 19178 non-null  float64
 14   club_name                    19178 non-null  object
 15   league_name                  19178 non-null  object
 16   league_level                 19178 non-null  float64
 17   club_position                19178 non-null  object
 18   club_jersey_number           19178 non-null  float64
 19   club_loaned_from             1102 non-null   object
 20   club_joined                  18076 non-null  object
 21   club_contract_valid_until    19178 non-null  float64
 22   nationality_id               19239 non-null  int64
 23   nationality_name             19239 non-null  object
 24   nation_team_id               759 non-null    float64
 25   nation_position              759 non-null    object
 26   nation_jersey_number         759 non-null    float64
 27   preferred_foot               19239 non-null  object
 28   weak_foot                    19239 non-null  int64
 29   skill_moves                  19239 non-null  int64
 30   international_reputation     19239 non-null  int64
 31   work_rate                    19239 non-null  object
 32   body_type                    19239 non-null  object
 33   real_face                    19239 non-null  object
 34   release_clause_eur           18063 non-null  float64
 35   player_tags                  1441 non-null   object
 36   player_traits                9398 non-null   object
 37   pace                         17107 non-null  float64
 38   shooting                     17107 non-null  float64
 39   passing                      17107 non-null  float64
 40   dribbling                    17107 non-null  float64
 41   defending                    17107 non-null  float64
 42   physic                       17107 non-null  float64
 43   attacking_crossing           19239 non-null  int64
 44   attacking_finishing          19239 non-null  int64
 45   attacking_heading_accuracy   19239 non-null  int64
 46   attacking_short_passing      19239 non-null  int64
 47   attacking_volleys            19239 non-null  int64
 48   skill_dribbling              19239 non-null  int64
 49   skill_curve                  19239 non-null  int64
 50   skill_fk_accuracy            19239 non-null  int64
 51   skill_long_passing           19239 non-null  int64
 52   skill_ball_control           19239 non-null  int64
 53   movement_acceleration        19239 non-null  int64
 54   movement_sprint_speed        19239 non-null  int64
 55   movement_agility             19239 non-null  int64
 56   movement_reactions           19239 non-null  int64
 57   movement_balance             19239 non-null  int64
 58   power_shot_power             19239 non-null  int64
 59   power_jumping                19239 non-null  int64
 60   power_stamina                19239 non-null  int64
 61   power_strength               19239 non-null  int64
 62   power_long_shots             19239 non-null  int64
 63   mentality_aggression         19239 non-null  int64
 64   mentality_interceptions      19239 non-null  int64
 65   mentality_positioning        19239 non-null  int64
 66   mentality_vision             19239 non-null  int64
 67   mentality_penalties          19239 non-null  int64
 68   mentality_composure          19239 non-null  int64
 69   defending_marking_awareness  19239 non-null  int64
 70   defending_standing_tackle    19239 non-null  int64
 71   defending_sliding_tackle     19239 non-null  int64
 72   goalkeeping_diving           19239 non-null  int64
 73   goalkeeping_handling         19239 non-null  int64
 74   goalkeeping_kicking          19239 non-null  int64
 75   goalkeeping_positioning      19239 non-null  int64
 76   goalkeeping_reflexes         19239 non-null  int64
 77   goalkeeping_speed            2132 non-null   float64
 78   ls                           19239 non-null  object
 79   st                           19239 non-null  object
 80   rs                           19239 non-null  object
 81   lw                           19239 non-null  object
 82   lf                           19239 non-null  object
 83   cf                           19239 non-null  object
 84   rf                           19239 non-null  object
 85   rw                           19239 non-null  object
 86   lam                          19239 non-null  object
 87   cam                          19239 non-null  object
 88   ram                          19239 non-null  object
 89   lm                           19239 non-null  object
 90   lcm                          19239 non-null  object
 91   cm                           19239 non-null  object
 92   rcm                          19239 non-null  object
 93   rm                           19239 non-null  object
 94   lwb                          19239 non-null  object
 95   ldm                          19239 non-null  object
 96   cdm                          19239 non-null  object
 97   rdm                          19239 non-null  object
 98   rwb                          19239 non-null  object
 99   lb                           19239 non-null  object
 100  lcb                          19239 non-null  object
 101  cb                           19239 non-null  object
 102  rcb                          19239 non-null  object
 103  rb                           19239 non-null  object
 104  gk                           19239 non-null  object
 105  player_face_url              19239 non-null  object
 106  club_logo_url                19178 non-null  object
 107  club_flag_url                19178 non-null  object
 108  nation_logo_url              759 non-null    object
 109  nation_flag_url              19239 non-null  object
dtypes: float64(16), int64(44), object(50)
memory usage: 16.1+ MB

In [6]:
for i in players_22.columns.tolist():
    if '_url' in i:
        players_22.drop(i, axis = 1, inplace= True)
    if '_id' in i:
        players_22.drop(i, axis = 1, inplace = True)

In [7]:
#Take out positions from the dataframe because judging the players by how good they perform at positions they perform well at can lead to biased desicions.
positions= ['gk', 'rb', 'rcb', 'cb', 'lcb', 'lb', 'rwb', 'rdm', 'cdm', 'ldm', 'lwb', 'rm', 'rcm', 'cm', 'lcm', 'lm', 'ram', 'cam', 'lam', 'rw', 'rf', 'cf', 'lf', 'lw', 'rs', 'st', 'ls']
players_22.drop(positions, axis = 1, inplace= True)

In [9]:
# More columns to drop with reasons
# 'short_name' : There is a long name which can act as an identifier
# 'club_position': The player's position in the club is less informative than performance metrics.
# 'club_jersey_number': Jersey numbers are not indicative of player skill or performance.
# 'club_joined': The date the player joined the club is less relevant compared to their performance metrics.
# 'club_contract_valid_until': Contract length is less directly tied to skill.
# 'real_face': Whether the player's face is realistic in the game is irrelevant to performance.
# Goalkeeping specific attributes are dropped since we are focusing on general player attributes:
# 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes'
columns_to_drop = [
    'short_name','club_position', 'club_jersey_number', 'club_joined', 
    'club_contract_valid_until', 'real_face', 
    'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 
    'goalkeeping_positioning', 'goalkeeping_reflexes', 'club_name', 'league_name'
]

# Drop the less relevant columns from the DataFrame
players_22 = players_22.drop(columns=columns_to_drop)

In [10]:
players_22.head()

,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,...,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_speed
0,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,170,72,...,44,40,93,95,75,96,20,35,24,NaN
1,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,1988-08-21,185,81,...,81,49,95,81,90,88,35,42,19,NaN
2,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,187,83,...,63,29,95,76,88,95,24,32,24,NaN
3,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,175,68,...,63,37,86,90,93,93,35,32,29,NaN
4,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,181,70,...,76,66,88,94,83,89,68,65,53,NaN

In [11]:
#Remove columns withe 30% or more null values too.
L= []
L_less = []
for i in players_22.columns:
    if((players_22[i].isnull().sum())<(0.3*(players_22.shape[0]))):
        L.append(i)
    else:
        L_less.append(i)
players_22 = players_22[L]

In [12]:
players_22

,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,...,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle
0,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,170,72,...,94,44,40,93,95,75,96,20,35,24
1,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,1988-08-21,185,81,...,87,81,49,95,81,90,88,35,42,19
2,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,187,83,...,93,63,29,95,76,88,95,24,32,24
3,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,175,68,...,81,63,37,86,90,93,93,35,32,29
4,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,181,70,...,91,76,66,88,94,83,89,68,65,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,宋德福,CDM,47,52,70000.0,1000.0,22,1999-01-02,180,64,...,30,52,42,38,43,42,37,38,43,48
19235,Caoimhin Porter,CM,47,59,110000.0,500.0,19,2002-03-18,175,70,...,38,49,39,51,49,44,47,37,44,47
19236,Nathan Logue-Cunningham,CM,47,55,100000.0,500.0,21,2000-02-07,178,72,...,34,51,38,45,46,39,36,38,44,48
19237,Luke Rudden,ST,47,60,110000.0,500.0,19,2002-04-23,173,66,...,41,34,14,47,40,49,47,10,14,11
19238,Emanuel Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,2002-02-06,167,61,...,36,55,42,47,46,35,36,33,31,37

In [13]:
players_names = pd.DataFrame(players_22['long_name'])
players_names
players_22.drop('long_name', axis = 1, inplace = True)

In [14]:
categorical_players = players_22.select_dtypes(exclude='number')
numerical_players = players_22.select_dtypes(include='number')

In [15]:
categorical_players.columns

Index(['player_positions', 'dob', 'nationality_name', 'preferred_foot',
       'work_rate', 'body_type'],
      dtype='object')

In [16]:
#Fill the null values in the numerical columns with the mean values
sc = SimpleImputer(strategy = 'mean')
scaled = sc.fit_transform(numerical_players)
numerical_players = pd.DataFrame(scaled, columns = numerical_players.columns)

In [17]:
#Fill the null values in the catergorical columns with the most frequent
sc = SimpleImputer(strategy = 'most_frequent')
scaled = sc.fit_transform(categorical_players)
categorical_players = pd.DataFrame(scaled, columns = categorical_players.columns)

In [18]:
#drop dob from categorical column since age already exists
categorical_players.drop(columns = ['dob', 'nationality_name', 'player_positions'], axis =1, inplace= True)

In [ ]:
#encoder = LabelEncoder()
#encoded_categories = categorical_players.apply(encoder.fit_transform)
#encoded_categories

In [19]:
encoded_categories = pd.get_dummies(categorical_players).astype(int)
encoded_categories

,preferred_foot_Left,preferred_foot_Right,work_rate_High/High,work_rate_High/Low,work_rate_High/Medium,work_rate_Low/High,work_rate_Low/Low,work_rate_Low/Medium,work_rate_Medium/High,work_rate_Medium/Low,...,body_type_Lean (170-),body_type_Lean (170-185),body_type_Lean (185+),body_type_Normal (170-),body_type_Normal (170-185),body_type_Normal (185+),body_type_Stocky (170-),body_type_Stocky (170-185),body_type_Stocky (185+),body_type_Unique
0,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19235,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19236,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19237,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19238,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [20]:
corr_matrix = numerical_players.corr()

In [21]:
correlations = corr_matrix["overall"].sort_values(ascending=False)

In [22]:
numeric_chosen = correlations[abs(correlations.values) >= 0.5]
numeric_chosen

overall                    1.000000
movement_reactions         0.871823
mentality_composure        0.708867
passing                    0.663519
potential                  0.644275
dribbling                  0.618419
wage_eur                   0.601001
power_shot_power           0.561180
value_eur                  0.553823
release_clause_eur         0.532528
mentality_vision           0.523025
attacking_short_passing    0.516788
Name: overall, dtype: float64

In [25]:

# Get the columns of numeric_chosen
chosen_columns = []
for variable, correlation in numeric_chosen.items():
    chosen_columns.append(variable)
# Create a new DataFrame with these chosen columns
numerical_players = numerical_players[chosen_columns]

In [26]:
new_players = pd.concat([numerical_players, encoded_categories], axis=1).reset_index(drop = True)

In [27]:
new_players

,overall,movement_reactions,mentality_composure,passing,potential,dribbling,wage_eur,power_shot_power,value_eur,release_clause_eur,...,body_type_Lean (170-),body_type_Lean (170-185),body_type_Lean (185+),body_type_Normal (170-),body_type_Normal (170-185),body_type_Normal (185+),body_type_Stocky (170-),body_type_Stocky (170-185),body_type_Stocky (185+),body_type_Unique
0,93.0,94.0,96.0,91.0,93.0,95.0,320000.0,86.0,78000000.0,144300000.0,...,0,0,0,0,0,0,0,0,0,1
1,92.0,93.0,88.0,79.0,92.0,86.0,270000.0,90.0,119500000.0,197200000.0,...,0,0,0,0,0,0,0,0,0,1
2,91.0,94.0,95.0,80.0,91.0,88.0,270000.0,94.0,45000000.0,83300000.0,...,0,0,0,0,0,0,0,0,0,1
3,91.0,89.0,93.0,86.0,91.0,94.0,270000.0,80.0,129000000.0,238700000.0,...,0,0,0,0,0,0,0,0,0,1
4,91.0,91.0,89.0,93.0,91.0,88.0,350000.0,91.0,125500000.0,232200000.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,47.0,53.0,37.0,46.0,52.0,48.0,1000.0,46.0,70000.0,114000.0,...,0,1,0,0,0,0,0,0,0,0
19235,47.0,49.0,47.0,50.0,59.0,46.0,500.0,49.0,110000.0,193000.0,...,0,1,0,0,0,0,0,0,0,0
19236,47.0,46.0,36.0,45.0,55.0,49.0,500.0,50.0,100000.0,175000.0,...,0,1,0,0,0,0,0,0,0,0
19237,47.0,48.0,47.0,36.0,60.0,48.0,500.0,48.0,110000.0,239000.0,...,0,1,0,0,0,0,0,0,0,0
19238,47.0,54.0,36.0,45.0,60.0,48.0,500.0,50.0,110000.0,217000.0,...,1,0,0,0,0,0,0,0,0,0

In [28]:
new_players.info(verbose= True, show_counts= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   overall                     19239 non-null  float64
 1   movement_reactions          19239 non-null  float64
 2   mentality_composure         19239 non-null  float64
 3   passing                     19239 non-null  float64
 4   potential                   19239 non-null  float64
 5   dribbling                   19239 non-null  float64
 6   wage_eur                    19239 non-null  float64
 7   power_shot_power            19239 non-null  float64
 8   value_eur                   19239 non-null  float64
 9   release_clause_eur          19239 non-null  float64
 10  mentality_vision            19239 non-null  float64
 11  attacking_short_passing     19239 non-null  float64
 12  preferred_foot_Left         19239 non-null  int32
 13  preferred_foot_Right        19239 non-null  int32
 14  work_rate_High/High         19239 non-null  int32
 15  work_rate_High/Low          19239 non-null  int32
 16  work_rate_High/Medium       19239 non-null  int32
 17  work_rate_Low/High          19239 non-null  int32
 18  work_rate_Low/Low           19239 non-null  int32
 19  work_rate_Low/Medium        19239 non-null  int32
 20  work_rate_Medium/High       19239 non-null  int32
 21  work_rate_Medium/Low        19239 non-null  int32
 22  work_rate_Medium/Medium     19239 non-null  int32
 23  body_type_Lean (170-)       19239 non-null  int32
 24  body_type_Lean (170-185)    19239 non-null  int32
 25  body_type_Lean (185+)       19239 non-null  int32
 26  body_type_Normal (170-)     19239 non-null  int32
 27  body_type_Normal (170-185)  19239 non-null  int32
 28  body_type_Normal (185+)     19239 non-null  int32
 29  body_type_Stocky (170-)     19239 non-null  int32
 30  body_type_Stocky (170-185)  19239 non-null  int32
 31  body_type_Stocky (185+)     19239 non-null  int32
 32  body_type_Unique            19239 non-null  int32
dtypes: float64(12), int32(21)
memory usage: 3.3 MB